# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker Image
      run: sudo docker build -t lbarrantes28/api-ec2-express .
    - name: Publish to Docker Hub
      run: sudo docker push lbarrantes28/api-ec2-express:latest
    # - name: Deploy to EC2 Instance
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     key: ${{ secrets.EC2_PRIVATE_KEY }}
  
  deploy:
    needs: build
    runs-on: [ec2-18-207-205-202.compute-1.amazonaws.com]
    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull lbarrantes28/api-ec2-express
      - name: Delete Old Container
        run: sudo docker rm -f ec2-express-api-container
      - name: Run Docker Container
        run: sudo docker run -d -p 5001:5001 -name ec2-express-api-container lbarrantes28/api-ec2-express

