# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    # - name: Login to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} | echo ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker Image
      run: docker build -t lbarrantes28/api-ec2-express .
    - name: Publish to Docker Hub
      run: docker push lbarrantes28/api-ec2-express:latest
  
  deploy:
    needs: build
    runs-on: [ip-172-31-83-131]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull lbarrantes28/api-ec2-express
      - name: Delete Old Container
        run: docker rm -f ec2-express-api-container
      - name: Run Docker Container
        run: docker run -d -p 5001:5001 -name ec2-express-api-container lbarrantes28/api-ec2-express

